### ISSUE TITLE
py3.6 encoding issue with negative numbers

### ISSUE THREAD

**Issue by gazzar** [aaronshifman/figurefirst#1]
Copying the issue description from the parent repository FlyRanch/figurefirst/#51

@aaronshifman reported
"I found an issue across both linux and windows in py3.6 (and I believe 3.7) here when "minus signs" are used - at least in the axis ticks (\u2212)"

My followup:

I just hit this problem too,starting to modify tutorial scripts for my own figures. I'm on Windows 10 Enterprise edition. I was in a Python 3.7 environment but I tried the same script in Python 3.5 and I've included the traceback from that:

```
Traceback (most recent call last):
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\site-packages\figurefirst\svg_to_axes.py", line 1235, in write_svg
    self.output_xml.writexml(outfile, encoding='utf-8')
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\xml\dom\minidom.py", line 1796, in writexml
    node.writexml(writer, indent, addindent, newl)
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\xml\dom\minidom.py", line 870, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\xml\dom\minidom.py", line 870, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\xml\dom\minidom.py", line 870, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\xml\dom\minidom.py", line 870, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\xml\dom\minidom.py", line 870, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\xml\dom\minidom.py", line 870, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\xml\dom\minidom.py", line 870, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\xml\dom\minidom.py", line 1185, in writexml
    writer.write("%s<!--%s-->%s" % (indent, self.data, newl))
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2212' in position 5: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "p:/manuscripts/widefield_compton_scatter_tomography/figs/figurefirst_example_script.py", line 45, in <module>
    layout.write_svg("two-up_output.svg")
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\site-packages\figurefirst\svg_to_axes.py", line 1239, in write_svg
    outfile.write(self.output_xml.toxml().encode('ascii', 'xmlcharrefreplace'))
TypeError: write() argument must be str, not bytes
```

If I make the change suggested by Aaron, the last part of the traceback changes to

```
Traceback (most recent call last):
  File "p:/manuscripts/widefield_compton_scatter_tomography/figs/figurefirst_example_script.py", line 45, in <module>
    layout.write_svg("two-up_output.svg")
  File "C:\Users\grub0002\anaconda3\envs\fifi\lib\site-packages\figurefirst\svg_to_axes.py", line 1240, in write_svg
    outfile.write(self.output_xml.toxml().encode('utf-8', 'xmlcharrefreplace'))
TypeError: write() argument must be str, not bytes
```

**Comment by aaronshifman** [comment]
/remind me deal with this in 2 weeks

**Comment by gazzar** [comment]
As mentioned in the source repository, the latest PR there fixes the problem for me too so we can close this issue.
